### ISSUE TITLE
protractor-demo to use directConnect

### ISSUE THREAD

**Issue by alecxe** [juliemr/protractor-demo#12]
As far as I understand, all protractor configs used in the `protractor-demo` are using either chrome of firefox, which means that `directConnect: true` can be used. As a benefit, less setup to try out the demo and howtos. Thanks.

**Comment by eduardoinnorway** [comment]
The issue is "directConnet = true" is set, this will never work, because it is expecting ":", why does the have "=" as default?

**Comment by juliemr** [comment]
Done!
